### ISSUE TITLE
no such file or directory 'peak_ipl/peak_ipl.hpp'

### ISSUE THREAD

**Issue by flynneva** [SherifN/peak_cam#6]
when I try to `catkin_make` this repo in my ROS workspace im seeing the following error.

```
/home/USER/code/ros/noetic/src/peak_cam/src/peak_cam.hpp:59:10: fatal error: peak_ipl/peak_ipl.hpp: No such file or directory
   59 | #include <peak_ipl/peak_ipl.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/USER/code/ros/noetic/src/peak_cam/src/peak_cam.cpp:39:
/home/continental/code/ros/noetic/src/peak_cam/src/peak_cam.hpp:59:10: fatal error: peak_ipl/peak_ipl.hpp: No such file or directory
   59 | #include <peak_ipl/peak_ipl.hpp>
```

any tips on how to get around this?

**Comment by shrutarv** [comment]
Hi,
@flynneva I am facing the same issue and am stuck on it since a week now. I am unable to understand how you resolved it. Could you please tell me where exactly did you make changes in the CMakeList.txt or could you please share the modified file. Do I need to change any additional changes?

Thank you in advance.

**Comment by flynneva** [comment]
@shrutarv its been awhile since I've touched this code, but my guess would be to double check the version of the IDS driver you have installed, and make sure that cmake can find it properly.

If you share exactly the warning or error you see maybe I can suggest more
